[project]
name = "aemo-monthly-extractor-to-xlsx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pytest>=8.4.1",
    "requests>=2.32.4",
]
